{{ if .Values.PROMRW_USER -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "log-exporter.fullname" . }}-promrw-credentials
  labels:
    {{- include "log-exporter.commonLabels" . | nindent 4 }}
data:
  PROMRW_USER: {{ .Values.PROMRW_USER | b64enc }}
  PROMRW_PASSWORD: {{ .Values.PROMRW_PASSWORD | b64enc }}
{{ end -}}
