{{ if eq "loki" (lower .Values.LME_DATASOURCE_TYPE) -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "log-exporter.fullname" . }}-loki-credentials
  labels:
    {{- include "log-exporter.commonLabels" . | nindent 4 }}
data:
  LOKI_USER: {{ .Values.LME_LOKI_USER | b64enc }}
  LOKI_PASSWORD: {{ .Values.LME_LOKI_PASSWORD | b64enc }}
{{ end -}}
